general_config:
  times: 1
  model_name: pFedG      # cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  algorithm: pfedg     # fed_acgan / fedacg_amp / fedcg/ fedzl_gan
  global_rounds: 50
  join_ratio: 0.25
  # optimization related
  optimizer: AdamW      # SGD / AdamW / Adam
  batch_size: 16
  local_steps: 1
  local_per_opt: False
  lr_scheduler: Exponential
  train_local_gan: False
# datasets related
#cifar10:
#  dataset: cifar10/
#  num_clients: 20
mnist:
  dataset: mnist/non_iid4robot(n20nc10d0.1)
  input_size: 28
  input_channels: 1
  num_clients: 20