general_config:
  times: 1
  model_name: pFedG   # harcnn, pFedG, cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  algorithm: pfedg   # pfedg / fed_acgan / fedcg/ fedzl_gan / FedAvg / FedProx / SCAFFOLD / FedDyn / FedGen /
                      # PerAvg / Ditto / FedAMP / APFL / APPLE / FedPer / FedRep / FedROD / FedBABU
                      # FedGH / GPFL / FedDistill / FedProto /
  global_rounds: 100
  join_ratio: 1.0
  # optimization related
  loss_fc: cross_entropy
  optimizer: SGD      # SGD / AdamW / Adam
  local_learning_rate: 0.005
  batch_size: 10
  local_steps: 1
  local_per_opt: False
  learning_rate_decay: False
  lr_scheduler: Exponential
  train_local_gan: False
# datasets related
cifar10:
  dataset: cifar10/non_iid4robot(n20nc10d0.1)
  num_clients: 20
  num_classes: 10
  input_channels: 3
  input_size: 32
#fmnist:
#  dataset: mnist/non_iid(n20nc10d0.1)
#  input_size: 28
#  input_channels: 1
#  num_clients: 20
#  num_classes: 10
#har:
#  dataset: har/non_iid
#  input_size: 28
#  input_channels: 9
#  num_clients: 30
#  num_classes: 6
#fer:
#  dataset: fer2013/non_iid(n20nc7d0.1)
#  num_clients: 20
#  num_classes: 7
#  input_channels: 1
#  input_size: 32