general_config:
  times: 1
  model_name: cnn      # cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  predictor: cnn
  algorithm: FedRep     # FedAvg / FedPer / FedProx / ditto / FedRep
  global_rounds: 200
  # optimization related
  optimizer: SGD      # SGD / AdamW / Adam
  batch_size: 4
  local_steps: 5
  local_per_opt: True
  lr_scheduler: Exponential
local_per_settings:
  local_per_optimizer: SGD
  local_per_lr_scheduler: Exponential
# datasets related
oulu:
  dataset: FER/oulu
  num_clients: 20
  join_ratio: 1.0
  # client local training settings
  local_learning_rate: 0.0005
BU3DFE:
  dataset: FER/BU3DFE
  num_clients: 20
  join_ratio: 1.0
ck:
  dataset: FER/ck
  num_clients: 20
  join_ratio: 1.0
jaffe:
  dataset: FER/jaffe
  num_clients: 10
  join_ratio: 1.0