general_config:
  times: 1
  model_name: simplenet      # cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  predictor: simplenet
  layer_idx: 12
  algorithm: FERv2     # FedPLAG / FedAvg / FedPer / FedProx / ditto / FedRep / FedAMP / FERv2
  global_rounds: 200
  join_ratio: 0.2
  # optimization related
  optimizer: AdamW      # SGD / AdamW / Adam
  batch_size: 4
  local_steps: 5
  local_per_opt: False
  lr_scheduler: Exponential
local_per_settings:
  local_per_optimizer: SGD
  local_per_lr_scheduler: Exponential
# datasets related
oulu:
  dataset: FER/oulu
  num_clients: 20
  # client local training settings
  local_learning_rate: 0.0005
BU3DFE:
  dataset: FER/BU3DFE
  num_clients: 20
ck:
  dataset: FER/ck
  num_clients: 20
jaffe:
  dataset: FER/jaffe
  num_clients: 10