general_config:
  times: 1
  model_name: lenet5      # lenet5
  algorithm: fedcg     # FedAvg / FedPer / FedProx / ditto / FedRep / FedAMP / FedCG
  global_rounds: 100
  join_ratio: 0.2
  # optimization related
  optimizer: AdamW      # SGD / AdamW / Adam
  batch_size: 32
  local_steps: 20
  local_per_opt: False
  lr_scheduler: Exponential
# datasets related
#cifar10:
#  dataset: cifar10/
#  num_clients: 20
mnist:
  dataset: mnist/non-iid_dir_ex(dir=0.3)/
  num_clients: 20
  input_size: 32
  input_channels: 3
#jaffe:
#  dataset: FER/jaffe
#  num_clients: 10
#  input_size: 32
#  input_channels: 3