general_config:
  times: 1
  model_name: lenet5      # cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  algorithm: fed_acgan     # fed_acgan / fedacg_amp
  global_rounds: 100
  join_ratio: 0.25
  # optimization related
  optimizer: SGD      # SGD / AdamW / Adam
  batch_size: 32
  local_steps: 5
  local_per_opt: False
  lr_scheduler: Exponential
# datasets related
#cifar10:
#  dataset: cifar10/
#  num_clients: 20
mnist:
  dataset: mnist/non_iid4robot(n20nc10d0.1)
  input_size: 28
  input_channels: 1
  num_clients: 20