general_config:
  times: 1
  model_name: simplenet      # cnn, simplenet, ConvNeXt_base, ConvNeXt_attom
  algorithm: ACGAN     # FedAvg / FedPer / FedProx / ditto / FedRep / FedAMP
  global_rounds: 100
  join_ratio: 0.2
  # optimization related
  optimizer: AdamW      # SGD / AdamW / Adam
  batch_size: 32
  local_steps: 5
  local_per_opt: False
  lr_scheduler: Exponential
# datasets related
#cifar10:
#  dataset: cifar10/
#  num_clients: 20
mnist:
  dataset: mnist/
  input_size: 28
  input_channels: 1
  num_clients: 20